# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17760aa6dde724f20163e3789a25fad182fec019e6b90c942b6f8d22953cd6266095af6e873c3ee404798651704066157a3417f46e5326ab351caa8c4f2fcfbc

test:
  secret_key_base: 373ca4c31b8a3692819cfc3983a975826e513cb6501d41957276be663e8f57fa26a1f2225577a59ea4b0cecd79ecc414e5ffbad8694bbafcabb9fded47da0c1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
